FROM node:10-buster-slim

ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

WORKDIR /nodeworlds/e2e
COPY package.json tsconfig.json yarn.lock report.js /nodeworlds/e2e/
RUN yarn install

COPY e2e /nodeworlds/e2e/e2e

CMD yarn e2e
